# configure database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: UserCenter
    password: pw123456@
    url: jdbc:mysql://usercenterdb.mysql.database.azure.com:3306/user?useSSL=true

#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306

  # Session timeout time
  session:
    timeout: 86400

server:
    port: 8080
    servlet:
      context-path: /api
      session:
        cookie:
          same-site: None
          secure: true
