# configure database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: UserCenter
    password: pw123456@
    url: jdbc:mysql://usercenterdb.mysql.database.azure.com:3306/user?useSSL=true
  # Session timeout time
  session:
    timeout: 86400
