# configure database
spring:
  application:
    name: user-center
  datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: wangtao@javaprojectsql
      password: pw12345678@
      url: jdbc:sqlserver://javaprojectsql.database.windows.net:1433;databaseName=JavaProjectSQL;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      #jdbc:sqlserver://javaprojectsql.database.windows.net:1433;database=JavaProjectSQL;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: UserCenter
#    password: pw123456@
#    url: jdbc:mysql://usercenterdb.mysql.database.azure.com:3306/user?useSSL=true

#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/user


  # Session timeout time
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: None
        secure: true


# mybatis-plus turn off camel case to call database correctly
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除字段名 name of attributes of deletion
      logic-delete-value: 1 # 逻辑已删除值 value represents deleted
      logic-not-delete-value: 0 # 逻辑未删除值 value represents undeleted